server:
  port: 9999

zuul:
  prefix: /api
  routes:
    test:
      path: /test/**
      serviceId: test

spring:
  application:
    name: http-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
          # for Azure
#      defaultZone: http://104.214.217.241:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

logging:
  file: application.log
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG